export interface Jogador {
  nome: string,
  email: string,
  celular: string,
  senha: string,
  posicaoX?: number,
  posicaoY?: number,
  posicaoZ?: number,
  fome: number,
  sono: number,
  forcaFisica: number,
  sede: number,
  dinheiro: number,
  creditos: number,
}
