"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//import "./rpg/index";
require("./rpg/browser/menuAdmin");
require("./rpg/admin/funcoes");
require("./rpg/Log/log");
require("./rpg/gui/player");
require("./rpg/player/data");
require("./rpg/profissoes/pizzaboy");
require("./betternotifs/index");
